[package]
name = "clparse"
version = "0.1.0"
authors = ["Marc Addeo <marcaddeo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = { version = "0.9.0", features = ["serde"] }
pulldown-cmark = "0.5.3"
chrono = { version = "0.4.7", features = ["serde"] }
derive_builder = "0.7.2"
failure = "0.1.5"
serde = "1.0.100"
serde_derive = "1.0.100"
serde_json = "1.0.40"
