[package]
name = "clparse"
version = "0.1.0"
authors = ["Marc Addeo <marcaddeo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
semver = "0.9.0"
pulldown-cmark = "0.5.3"
chrono = "0.4.7"
derive_builder = "0.7.2"
