---
name: Build and Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build and Release ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-unknown-linux-musl
            os: ubuntu-20.04
          - target: x86_64-apple-darwin
            os: macOS-latest
          - target: aarch64-apple-darwin
            os: macOS-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.platform.target }}
          toolchain: stable
          args: "--locked --release"
          strip: true

      - name: Generate SHA-256
        run: shasum -a 256 target/${{ matrix.platform.target }}/release/clparse | cut -d ' ' -f 1 > target/${{ matrix.platform.target }}/release/clparse.sha256

      - name: Create release archive
        uses: a7ul/tar-action@v1.1.0
        with:
          command: c
          cwd: target/${{ matrix.platform.target }}/release
          files: |
            clparse
          outPath: clparse-${{ github.ref_name }}-${{ matrix.platform.target }}.tar.gz

      - name: Release binary and SHA-256 checksum to GitHub
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.platform.target }}/release/clparse-${{ github.ref_name }}-${{ matrix.platform.target }}.tar.gz
            target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}.sha256
